### ISSUE TITLE
报刀测试！

### ISSUE THREAD

**Issue by JohndeVostok** [umi-pcr/clan-issue#5]
请在此处提交出刀记录，格式如下：

ID:轮次-阶段:伤害

例如： 高坂海美:2-B1:100000

**Comment by itachi4869** [comment]
南柯:2-B2:100000

**Comment by Yukino-0** [comment]
雪乃（0:2-B3:100000

**Comment by AIstroemeria** [comment]
南飞雁:2-B3:6000000

**Comment by Duel25** [comment]
Duel:2-B6:10000000

**Comment by elsssssssssssssssss** [comment]
Duel:2-B1:1
Duel:2-B2:1
Duel:2-B3:1
Duel:2-B4:1
Duel:2-B5:1
